// <auto-generated />
using System;
using MasterMind.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MasterMind.Data.Migrations
{
    [DbContext(typeof(GameDataContext))]
    [Migration("20191020003827_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("MasterMind.Data.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameID");

                    b.ToTable("mmGame");
                });

            modelBuilder.Entity("MasterMind.Data.GamePattern", b =>
                {
                    b.Property<int>("GamePatternID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePeg1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePeg2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePeg3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePeg4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyPeg1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPeg2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPeg3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPeg4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("GamePatternID");

                    b.HasIndex("GameID");

                    b.ToTable("mmGamePattern");
                });

            modelBuilder.Entity("MasterMind.Data.GamePattern", b =>
                {
                    b.HasOne("MasterMind.Data.Game", "Game")
                        .WithMany("Patterns")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
